//! Collecting what a handler leaves behind into a [`SpelOutput`].
//!
//! v0.2.5 retired the idea of a program *claiming* an account. Writing data to
//! an account nobody owns is itself the claim, and an account left unowned may
//! simply not carry data. A handler therefore says only what each declared
//! account should look like once it has run; the entry point generated by
//! `#[lez_program]` pairs those with the pre-states LEZ supplied and derives
//! the `AccountStateDiff` values the protocol wants.

use nssa_core::account::{Account, AccountWithMetadata};
use nssa_core::program::{ChainedCall, ValidityWindow};

use crate::types::{IntoPostAccount, SpelOutput};

// ── IntoPostAccount implementations ─────────────────────────────────────

impl IntoPostAccount for Account {
    fn into_post_account(self) -> Account {
        self
    }
}

impl IntoPostAccount for &Account {
    fn into_post_account(self) -> Account {
        self.clone()
    }
}

// A handler receives its accounts as `AccountWithMetadata` and usually hands the
// same values straight back, so accept those too rather than making every
// handler write `.account` on every line. The metadata itself is not part of a
// post-state: `account_id` is fixed by the declaration and `is_authorized` is
// the protocol's to decide, so only the account travels.
impl IntoPostAccount for AccountWithMetadata {
    fn into_post_account(self) -> Account {
        self.account
    }
}

impl IntoPostAccount for &AccountWithMetadata {
    fn into_post_account(self) -> Account {
        self.account.clone()
    }
}

// ── SpelOutput::execute ─────────────────────────────────────────────────

impl SpelOutput {
    /// Build a `SpelOutput` from the accounts a handler produced, in the order
    /// the instruction declared them.
    ///
    /// Order is load-bearing: the generated entry point zips these against the
    /// pre-states positionally to build the diffs, so an account must not be
    /// dropped or reordered even when the handler left it untouched.
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// // Inside a handler generated by #[lez_program]:
    /// Ok(SpelOutput::execute(
    ///     vec![state.account.clone(), authority.account.clone()],
    ///     vec![],  // chained calls
    /// ))
    /// ```
    pub fn execute(
        accounts: impl IntoIterator<Item = impl IntoPostAccount>,
        calls: Vec<ChainedCall>,
    ) -> Self {
        let post_states = accounts
            .into_iter()
            .map(IntoPostAccount::into_post_account)
            .collect();
        Self {
            post_states,
            chained_calls: calls,
            block_validity_window: ValidityWindow::new_unbounded(),
            timestamp_validity_window: ValidityWindow::new_unbounded(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;


    /// A chained call naming `program` as the callee.
    ///
    /// v0.2.5 chained calls carry only account *ids*: the protocol resolves each
    /// account's value and its authorization from its own tracked state, so a
    /// caller can no longer hand the callee an account it has marked authorized.
    fn call_to(program: u8) -> ChainedCall {
        ChainedCall {
            program_account_id: nssa_core::account::AccountId::new([program; 32]),
            pre_state_ids: vec![nssa_core::account::AccountId::new([program; 32])],
            instruction_data: vec![],
            pda_seeds: vec![],
        }
    }

    #[test]
    fn execute_carries_chained_calls() {
        let output = SpelOutput::execute(vec![Account::default()], vec![call_to(7)]);
        assert_eq!(output.post_states.len(), 1);
        assert_eq!(
            output.chained_calls.len(),
            1,
            "the call must reach the output"
        );
        assert_eq!(
            output.chained_calls[0].program_account_id,
            nssa_core::account::AccountId::new([7; 32])
        );
    }

    #[test]
    fn execute_preserves_chained_call_order() {
        // Order is the execution order downstream, so it must not be reshuffled.
        let output = SpelOutput::execute(
            vec![Account::default()],
            vec![call_to(1), call_to(2), call_to(3)],
        );
        let ids: Vec<u8> = output
            .chained_calls
            .iter()
            .map(|c| c.program_account_id.value()[0])
            .collect();
        assert_eq!(ids, vec![1, 2, 3]);
    }



    /// Convenience helper: returns a `SpelOutput` with no accounts or calls.
    /// Reduces boilerplate in validity-window tests below.
    fn empty_output() -> SpelOutput {
        SpelOutput::execute(Vec::<Account>::new(), vec![])
    }



    #[test]
    fn execute_empty() {
        let output = SpelOutput::execute(Vec::<Account>::new(), vec![]);
        assert!(output.post_states.is_empty());
        assert!(output.chained_calls.is_empty());
    }





    // ── Validity window tests ────────────────────────────────────────────

    /// Existing programs that don't call any validity window builder get unbounded
    /// windows, which matches the prior hard-coded behavior.
    #[test]
    fn default_output_has_unbounded_windows() {
        let output = empty_output();
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
        assert_eq!(output.timestamp_validity_window.start(), None);
        assert_eq!(output.timestamp_validity_window.end(), None);
    }


    #[test]
    fn with_block_validity_window_range_from() {
        let output = empty_output().with_block_validity_window(42u64..);
        assert_eq!(output.block_validity_window.start(), Some(42));
        assert_eq!(output.block_validity_window.end(), None);
    }

    #[test]
    fn with_block_validity_window_range_to() {
        let output = empty_output().with_block_validity_window(..100u64);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), Some(100));
    }

    #[test]
    fn with_block_validity_window_unbounded() {
        let output = empty_output().with_block_validity_window(..);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
    }

    #[test]
    fn try_with_block_validity_window_valid_range() {
        let output = empty_output()
            .try_with_block_validity_window(10u64..20)
            .expect("10..20 is a valid range");
        assert_eq!(output.block_validity_window.start(), Some(10));
        assert_eq!(output.block_validity_window.end(), Some(20));
    }

    #[test]
    fn try_with_block_validity_window_empty_range_errors() {
        let result = empty_output().try_with_block_validity_window(5u64..5);
        assert!(result.is_err(), "empty range should return Err");
    }

    #[test]
    #[allow(clippy::reversed_empty_ranges)]
    fn try_with_block_validity_window_inverted_range_errors() {
        let result = empty_output().try_with_block_validity_window(10u64..5);
        assert!(result.is_err(), "inverted range should return Err");
    }

    /// RangeFull (`..`) is an infallible conversion — use the infallible
    /// `with_block_validity_window` variant, not `try_with_*`.
    #[test]
    fn with_block_validity_window_range_full_succeeds() {
        let output = empty_output().with_block_validity_window(..);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
    }

    /// RangeFull (`..`) is an infallible conversion — use the infallible
    /// `with_timestamp_validity_window` variant, not `try_with_*`.
    #[test]
    fn with_timestamp_validity_window_range_full_succeeds() {
        let output = empty_output().with_timestamp_validity_window(..);
        assert_eq!(output.timestamp_validity_window.start(), None);
        assert_eq!(output.timestamp_validity_window.end(), None);
    }

    #[test]
    fn with_timestamp_validity_window_range_from() {
        let output = empty_output().with_timestamp_validity_window(1_700_000_000u64..);
        assert_eq!(
            output.timestamp_validity_window.start(),
            Some(1_700_000_000)
        );
        assert_eq!(output.timestamp_validity_window.end(), None);
    }

    #[test]
    fn try_with_timestamp_validity_window_valid_range() {
        let output = empty_output()
            .try_with_timestamp_validity_window(1_000u64..2_000)
            .expect("1000..2000 is a valid range");
        assert_eq!(output.timestamp_validity_window.start(), Some(1_000));
        assert_eq!(output.timestamp_validity_window.end(), Some(2_000));
    }

    #[test]
    fn try_with_timestamp_validity_window_empty_range_errors() {
        let result = empty_output().try_with_timestamp_validity_window(99u64..99);
        assert!(result.is_err());
    }

    #[test]
    #[allow(clippy::reversed_empty_ranges)]
    fn try_with_timestamp_validity_window_inverted_range_errors() {
        let result = empty_output().try_with_timestamp_validity_window(2_000u64..1_000);
        assert!(result.is_err(), "inverted range should return Err");
    }

    #[test]
    fn into_parts_returns_all_fields() {
        let output = SpelOutput::execute(Vec::<Account>::new(), vec![])
            .with_block_validity_window(5u64..)
            .try_with_timestamp_validity_window(100u64..200)
            .unwrap();

        let parts = output.into_parts();
        let post_states = parts.post_states;
        let chained_calls = parts.chained_calls;
        let block_window = parts.block_validity_window;
        let ts_window = parts.timestamp_validity_window;
        assert!(post_states.is_empty());
        assert!(chained_calls.is_empty());
        assert_eq!(block_window.start(), Some(5));
        assert_eq!(block_window.end(), None);
        assert_eq!(ts_window.start(), Some(100));
        assert_eq!(ts_window.end(), Some(200));
    }
}
